### Basic Authorization鉴权 不通过
GET http://localhost:8080/auth/invoke

### Basic Authorization鉴权 通过
GET http://localhost:8080/auth/invoke
Authorization: Basic YWNleHk6YWNleHk=

### 404
GET localhost:8080/auth/invoke1

### demo/more
GET localhost:8080/demo/more